<?php

return [
    'categories_cache_prefix' => 'categories_',
    'categories_thumbnail_cache_prefix' => 'categories_thumbnail_',
    'categories_total_years' => 10,
    'classic_game_date' => '2009-01-01',
    'classic_platform_year' => '2006',
    'collections_per_page' => 25,
    'community_spotlight_users_cache_duration' => 30 * 60,
    'community_spotlight_users_days_range' => 7,
    'community_spotlight_users_total' => 12,
    'community_spotlight_users_total_mobile' => 6,
    'contributions_per_page' => 21,
    'contributions_per_page_mobile' => 15,
    'default_collections' => [
        'playing',
        'favorites',
        'wishlist'
    ],
    'exclude_characteristics_from_ranking' => [
        'compilation',
        'expansion'
    ],
    'feed_months_period' => 1,
    'feed_per_page' => 25,
    'feed_per_page_reviews' => 20,
    'feed_cache_minutes' => 60 * 60,
    'home_list_slug' => 'featured-games',
    'home_list_cache_name' => 'home-list',
    'home_list_total_items' => 1000,
    'game_index_total_collections' => 8,
    'game_index_total_collections_mobile' => 3,
    'game_index_total_discussions' => 5,
    'game_index_total_screenshots' => 6,
    'game_index_total_raters' => 23,
    'game_index_total_relateds' => 7,
    'game_index_total_reviews' => 4,
    'game_index_total_reviews_mobile' => 4,
    'game_minimum_to_show_ranking' => 4,
    'game_review_other_reviews' => 4,
    'game_collections_per_page' => 16,
    'game_ratings_per_page' => 12,
    'game_relateds_per_page' => 20,
    'game_reviews_per_page' => 8,
    'game_reviews_per_page_mobile' => 10,
    'home_total_sliders' => 11,
    'home_total_sliders_mobile' => 10,
    'items_per_slider' => 35,
    'items_per_slider_mobile' => 10,
    'list_score_for_criteria' => 9.3,
    'list_score_for_praised_games' => 8.8,
	'locale' => '',
	'locale_column_suffix' => '',
    'minimum_characters_to_contact' => 25,
	'minimum_characters_to_review' => 150,
    'minimun_collection_games_to_fire_event' => 10,
	'minimum_ratings_to_rank' => 8,
    'minimum_items_to_slider' => 6,
    'multiplier_collection' => 2,
    'multiplier_contribution' => 2,
    'multiplier_rating' => 1,
    'multiplier_review' => 3,
    'newcomer_level_ceil' => 5,
	'per_page' => 100,
    'per_page_mobile' => 40,
	'per_page_user' => 24,
    'relevant_review_minimum_characters' => 600,
    'search_results' => 7,
    'search_results_mobile' => 10,
    'ranking_cache_minutes' => 30 * 60,
    'ranking_per_page' => 100,
    'ranking_starting_year' => 1990,
    'ratings_per_page' => 20,
    'reviews_per_page' => 20,
	'trending_days_future_games' => 35,
	'trending_days_games' => 90,
	'trending_days_users' => 14,
    'user_index_total_best_recent_ratings' => 5,
    'user_index_total_best_recent_ratings_mobile' => 3,
    'user_index_total_collections' => 2,
    'user_index_total_collections_mobile' => 2,
    'user_index_total_contributions' => 10,
    'user_index_total_contributions_mobile' => 2,
    'user_index_total_favorite_games' => 10,
    'user_index_total_favorite_games_mobile' => 4,
    'user_index_total_followings' => 20,
    'user_index_total_followings_mobile' => 6,
    'user_index_total_followers' => 20,
    'user_index_total_followers_mobile' => 6,
    'user_index_total_most_liked_reviews' => 2,
    'user_index_total_most_liked_reviews_mobile' => 2,
    'user_index_total_playing_games' => 3,
    'user_index_total_playing_games_mobile' => 4,
    'user_index_total_ratings' => 5,
    'user_index_total_ratings_mobile' => 4,
    'user_index_total_reviews' => 4,
    'user_index_total_reviews_mobile' => 3,
    'user_index_total_wishlist_games' => 10,
    'user_index_total_wishlist_games_mobile' => 4,
    'user_total_ratings' => 20,
    'user_total_ratings_mobile' => 10,
    'user_total_reviews' => 8,
    'user_total_collections' => 12,
    'user_total_contributions' => 18,
    'user_total_contributions_mobile' => 10,
    'user_total_followers' => 24,
    'user_total_following' => 24,
    'user_total_liked_reviews' => 8,
    'user_total_favorites' => 45,
    'user_total_wishlist' => 45
];